apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana-gateway
  namespace: istio-system
  annotations: 
    external-dns.alpha.kubernetes.io/hostname: grafana.prod.skynetx.me,cve.prod.skynetx.me
spec:
  selector:
    app: istio-ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "grafana.prod.skynetx.me"
    tls:
      mode: SIMPLE
      credentialName: grafana-cert-tls
  - port:
      number: 443
      name: https-streamlit
      protocol: HTTPS
    hosts:
    - "cve.prod.skynetx.me"
    tls:
      mode: SIMPLE
      credentialName: streamlit-cert-tls