apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cve-consumer.fullname" . }}
spec:
  replicas: 1 # Specify the number of replicas
  selector:
    matchLabels:
      app: {{ include "cve-consumer.fullname" . }} # Ensure this matches the template metadata labels
  template:
    metadata:
      labels:
        app: {{ include "cve-consumer.fullname" . }} # Labels to match the selector
    spec:
      initContainers:
        - name: flyway-migration
          image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}"
          imagePullPolicy: Always
          env:
            {{- range .Values.initContainer.env }}
            - name: {{ .name }}
              {{- if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- else }}
              value: {{ .value | quote }}
              {{- end }}
            {{- end }}
          command: ["flyway", "migrate"]
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- else }}
              value: {{ .value | quote }}
              {{- end }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3    
      imagePullSecrets:
        - name: docker-hub-pat