apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cve-deny-all
  namespace: cve-consumer
spec:
  podSelector:
    matchLabels:
      app: cve-db
  policyTypes:
  - Ingress


---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-network-policy
  namespace: cve-consumer
spec:
  podSelector:
    matchLabels:
      app: cve-db
  ingress:
  - ports:
    - port: 5432
    from:
    - podSelector:
        matchLabels:
          app: cve-consumer