apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: example-psp
spec:
  allowedCapabilities:
  - NET_ADMIN
  - NET_RAW



#kubectl label namespace my-secure-namespace pod-security.kubernetes.io/enforce=privileged
 