apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch
data:
  cluster.name: {{ .Values.clusterName }}
  http.port: {{ .Values.fluentBitHttpPort | quote }}
  http.server: {{ .Values.fluentBitHttpServer | quote }}
  logs.region: {{ .Values.regionName }}
  read.head: {{ .Values.fluentBitReadFromHead | quote }}
  read.tail: {{ .Values.fluentBitReadFromTail | quote }}
